[package]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false
[kubernetes.context_aliases]
# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[gcloud]
format = 'on [$symbol($project)]($style) '

[java]
disabled = true
